---
###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Benevides Mamede Jr - June/2021
# Updates:
#
###############################################################################
# tasks file for roles/finish

- name: Clean up
  file:
    path: /tmp/ansbile/{{ ansible_user_id|lower }}
    state: absent
