---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh

  tasks:
    - name: Execute an operator command to show active jobs
      local_action:
        module: zos_operator
        cmd: 'd u,all'
        register: duall
      
    - name: Display it
      debug:
        var: duall.content
