---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
  environment: "{{ environment_vars }}"

  tasks:
    - name: Execute an operator command to show active jobs
      command: 'd u,all'
      register: duall
      
    - name: Display it
      debug:
        var: duall.content
