---
- name: Change passphrase
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"

  tasks:
    - name: Execute TSO command to change passphrase
      command: "PASSWORD PHRASE('{{ passphrase_current }}' '{{ passphrase_new }}')"
