---
- name: Send ssh key
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Send ssh key
      command: type $env:/Users/lucasvasconcelos/Desktop\Authorized_Keys.pub | ssh br02466@{{ hosts_cirats_inventory }} "mkdir -p .ssh; cat >> .ssh/authorized_keys"
