---
- name: Send ssh key
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Send ssh key
      command: type $env:/Users/lucasvasconcelos/Downloads\Authorized_Keys.pub | ssh br11556@{{ hosts_cirats_inventory }} "mkdir -p .ssh; cat >> .ssh/authorized_keys"
