###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Benevides Mamede Jr - October/2020
# Updates:
#  May/2021 - redesigned to simplify use
#  June/2021 - implemented use of roles
#
###############################################################################
---
- name: Step3 - Get missing APARS
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh

  tasks:
    - name: start
      include_role:
        name: start

    - name: Install procs
      include_role:
        name: install_procs
      vars:
        procnames:
          - getsysinfo
          - getsysvar

    - name: Get system infos
      include_role:
        name: get_infos
      vars:
        infos:
          - StaticConfig
          - SYSR1
          - TSID

    - name: JOBS loop
      include_role:
        name: submit_jobs
      vars:
        src: D
        jobnames:
          - BLD1PREC

    - name: Get ORDPRE
      command: dtail -n -100 '{{ ds_sysouts }}(ORDERPRE)'
      register: ddout

    - name: Print results
      debug:
        var: ddout.stdout_lines

    - name: Submit static jobs
      include_role:
        name: submit_jobs
      vars:
        src: S
        jobnames: "{{ jobs_static_preGSD }}"
      when: jobs_static_preGSD is iterable

    - name: Finish
      include_role:
        name: finish

    - name: List RCs
      debug:
        var: jobsrc
