###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Benevides Mamede Jr - October/2020
# Updates:
#  May/2021 - redesigned to simplify use
#  June/2021 - implemented use of roles 
#
###############################################################################---
- name: Util - onboard new system
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh

  tasks:
    - name: start
      include_role:
        name: start

    - name: Install procs
      include_role:
        name: install_procs
      vars:
        procnames:
          - getsysinfo
          - getsysvar

    - name: Get system infos
      include_role:
        name: get_infos
      vars:
        infos:
          - SYSR1
          - CATVOL

    - name: Adjust variables
      set_fact:
        new: "{{ cur[0: 4:] }}{{ sysres_new_suffix }}1 "
      when: cur[:5 :5] != 'Y'

    - name: Adjust variables
      set_fact:
        new: "{{ cur[0: 6:] }}{{ sysres_new_suffix }} "
      when: cur[:5 :5] == 'Y'

    - name: Display error message
      debug:
        msg: 
        - "--ERROR!" 
        - "New sysres volser formed {{ new }} is equal current sysres in use {{ cur }}. Verify." 
        - " "
      when: cur == new

    - name: if OK continue
      block:        
      - name: Create datasets for cycle {{ hld }}
        zos_data_set:
          batch:
            - name: '{{ ds_sysouts }}'
              type: PDS
              space_primary: 5
              space_type: CYL
              record_format: FBA
              record_length: 121
            - name: '{{ ds_sysouts }}.SYSLOG'
              type: SEQ
              space_primary: 12
              space_type: CYL
              record_format: VB
              record_length: 200        
            - name: '{{ ds_cntl }}'
              type: PDSE
              space_primary: 11
              space_type: CYL
              record_format: FB
              record_length: 80
            - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE.MODEL'
              type: SEQ
              space_primary: 11
              space_type: CYL
              record_format: FB
              record_length: 1024            
            - name: '{{ ds_cntl }}.ANSIBLE.RESTORE'
              type: PDSE
              state: absent
            - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZDUMP'
              type: SEQ
              state: absent
            - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZDUMP1'
              type: SEQ
              state: absent
            - name: '{{ds_load }}'
              type: SEQ
              state: absent
            - name: '{{ds_procs }}'
              type: SEQ
              state: absent
            - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE'
              type: SEQ
              state: absent

      - name: transfer terse dataset
        zos_copy:
          src: "{{ playbook_dir }}/files/unloads/install_terse.bin"
          dest: "{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE"
          model_ds: "{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE.MODEL"
          is_binary: true
          ignore_sftp_stderr: true
          force: true

      - name: unterse and restore it
        include_role:
          name: submit_jobs
        vars:
          src: D
          jobnames:
          - restore
          - restore_cntl

      - name: Install procs
        include_role:
          name: install_procs
        vars:
          procnames:
            - IPLINFO

      - name: Get system infos
        include_role:
          name: get_infos
        vars:
          infos:
            - IODEV
            - LOAD
            - SMFID
            - SYM
            - SYSCLONE
            - SYSNAME
            - SYSP
            - TSID

      - name: Update BLDINCL member
        zos_lineinfile:
          src: '{{ ds_cntl }}.ANSIBLE.RESTORE(BLDINCL)'
          regexp: '{{ item.From }}'
          line: '{{ item.To }}'
        with_items:
          - {From: 'HLD=', To: "//   SET  HLD={{ hld }}"}
          - {From: 'CUR=', To: "//   SET  CUR={{ cur }}"}
          - {From: 'NEW=', To: "//   SET  NEW={{ new }}"}
          - {From: 'SID=', To: "//   SET  SID={{ tsid }}"}

      - name: Submit dynamic jobs
        include_role:
          name: submit_jobs
        vars:
          src: D
          jobnames:
            - pds_update
            - copy_cntl

      - name: Get BLDINCL
        shell: dtail -n -100 '{{ds_cntl }}(BLDINCL)'
        register: bldincl

      - name: Display it
        debug:
          var: bldincl.stdout_lines

      - name: Get host vars
        local_action: 
          module: shell
          _raw_params:  "/bin/cat group_vars/{{ group_names.0 }}.yml"
        register: hvars

      - name: Display it
        debug:
          var: hvars.stdout_lines
      when: cur != new

    - name: Clean up
      zos_data_set:
        batch:
          - name: "{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE"
            state: absent

          - name: "{{ ds_prefix }}.{{ group_names.0 }}.ZTERSE.MODEL"
            state: absent

          - name: '{{ ds_cntl }}.ANSIBLE.RESTORE'
            state: absent
          - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZDUMP'
            type: SEQ
            state: absent
          - name: '{{ ds_prefix }}.{{ group_names.0 }}.ZDUMP1'
            type: SEQ
            state: absent

    - name: Finish
      include_role:
        name: finish
