###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Benevides Mamede Jr - October/2020
# Updates:
#  May/2021 - redesigned to simplify use
#  June/2021 - implemented use of roles 
#
###############################################################################---
- name: Util - Clean NEW sysres
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh
#  vars_prompt:
#    - name: continue
#      prompt: "This will initialize new SYSRES and delete all OMVS related. Do you want to continue? (Yes/No)"
#      private: no

  tasks:
    - name: block
      block:
      - name: start
        include_role:
          name: start

      - name: Get system infos
        include_role:
          name: get_infos
        vars:
          infos:
            - StaticConfig

      - name: Submit static jobs
        include_role:
          name: submit_jobs
        vars:
          src: S
          jobnames: 
            jobnames: 
              - '####REQ4'
              - '####REQ5'

      - name: Finish
        include_role:
          name: finish

      - name: List RCs
        debug:
          var: jobsrc
      when: continue == 'Yes'
