---
###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Benevides Mamede Jr - June/2021
# Updates:
#
###############################################################################
# tasks file for roles/submit_jobs

- name: Submit jobs
  include_tasks: files/run_dynamic_jobs.yaml
  loop: "{{ jobnames }}"
  loop_control:
    loop_var: job
  when: src == "D"

- name: Submit jobs
  include_tasks: files/run_static_jobs.yaml
  loop: "{{ jobnames }}"
  loop_control:
    loop_var: job
  when: src  == "S"
